-- MySQL Script generated by MySQL Workbench
-- Sun Jun  3 19:20:54 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema yourfoundsdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `yourfoundsdb`.`categoryId`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yourfoundsdb`.`categoryId` (
  `category_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `desciption` VARCHAR(45) NULL,
  PRIMARY KEY (`category_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yourfoundsdb`.`expense`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yourfoundsdb`.`expense` (
  `expense_id` INT NOT NULL AUTO_INCREMENT,
  `sum` DECIMAL(18,2) NOT NULL,
  `category_id` INT NOT NULL,
  `date` DATE NOT NULL,
  `time` TIME(0) NOT NULL,
  `comment` VARCHAR(45) NULL,
  PRIMARY KEY (`expense_id`),
  INDEX `fk_expense_category1_idx` (`category_id` ASC),
  CONSTRAINT `fk_expense_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `yourfoundsdb`.`categoryId` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yourfoundsdb`.`account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yourfoundsdb`.`account` (
  `account_id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL,
  `summary` DECIMAL(18,2) NOT NULL,
  `description` VARCHAR(300) NOT NULL,
  PRIMARY KEY (`account_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yourfoundsdb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yourfoundsdb`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NULL,
  `surname` VARCHAR(45) NULL,
  `expense_id` INT NOT NULL,
  `account_id` INT NOT NULL,
  PRIMARY KEY (`user_id`),
  INDEX `fk_user_expense_idx` (`expense_id` ASC),
  INDEX `fk_user_account1_idx` (`account_id` ASC),
  CONSTRAINT `fk_user_expense`
    FOREIGN KEY (`expense_id`)
    REFERENCES `yourfoundsdb`.`expense` (`expense_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_account1`
    FOREIGN KEY (`account_id`)
    REFERENCES `yourfoundsdb`.`account` (`account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yourfoundsdb`.`categoryId`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yourfoundsdb`.`categoryId` (
  `category_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `desciption` VARCHAR(45) NULL,
  PRIMARY KEY (`category_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
