-- MySQL Script generated by MySQL Workbench
-- Sun Jun  3 19:20:54 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema notspenddb
-- -----------------------------------------------------
CREATE DATABASE  IF NOT EXISTS `notspenddb`
  CHARACTER SET utf8
  COLLATE utf8_general_ci;
-- -----------------------------------------------------
-- Table `notspenddb`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `notspenddb`.`category` (
  `category_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `desciption` VARCHAR(50) NULL,
  PRIMARY KEY (`category_id`))
ENGINE = InnoDB CHARACTER SET utf8 COLLATE utf8_general_ci;


-- -----------------------------------------------------
-- Table `notspenddb`.`expense`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `notspenddb`.`expense` (
  `expense_id` INT NOT NULL AUTO_INCREMENT,
  `sum` DECIMAL(18,2) NOT NULL,
  `category_id` INT NOT NULL,
  `date` DATE NOT NULL,
  `time` TIME(0) NOT NULL,
  `comment` VARCHAR(50) NULL,
  PRIMARY KEY (`expense_id`),
  INDEX `fk_expense_category1_idx` (`category_id` ASC),
  CONSTRAINT `fk_expense_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `notspenddb`.`category` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB CHARACTER SET utf8 COLLATE utf8_general_ci;


-- -----------------------------------------------------
-- Table `notspenddb`.`account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `notspenddb`.`account` (
  `account_id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(50) NOT NULL,
  `summary` DECIMAL(18,2) NOT NULL,
  `description` VARCHAR(300) NOT NULL,
  PRIMARY KEY (`account_id`))
ENGINE = InnoDB CHARACTER SET utf8 COLLATE utf8_general_ci;


-- -----------------------------------------------------
-- Table `notspenddb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `notspenddb`.`user` (
  `username` VARCHAR(50) NOT NULL UNIQUE,
  `email` VARCHAR(50) NOT NULL,
  `password` VARCHAR(200) NOT NULL,
  `name` VARCHAR(50) NULL,
  `surname` VARCHAR(50) NULL,
  `expense_id` INT NOT NULL,
  `account_id` INT NOT NULL,
  PRIMARY KEY (`username`),
  INDEX `fk_user_expense_idx` (`expense_id` ASC),
  INDEX `fk_user_account1_idx` (`account_id` ASC),
  CONSTRAINT `fk_user_expense`
    FOREIGN KEY (`expense_id`)
    REFERENCES `notspenddb`.`expense` (`expense_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_account1`
    FOREIGN KEY (`account_id`)
    REFERENCES `notspenddb`.`account` (`account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB CHARACTER SET utf8 COLLATE utf8_general_ci;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
